### ISSUE TITLE
How to grab XML file on Desktop

### ISSUE THREAD

**Issue by balistrerin** [nicklockwood/XMLDictionary#54]
Is this how to correctly grab the XML file because it doesn't seem to letting me grab the XML file so I can parse the data?  

    NSString *filePath = [[NSBundle mainBundle] pathForResource:@"/Users/mycomputer/Desktop/foo" ofType:@"xml"];
    NSDictionary *xmlDoc = [NSDictionary dictionaryWithXMLFile:filePath];
    
    if(xmlDoc){
        NSLog(@"Grabbed the doc");
    }else{
        NSLog(@"failed to grab the doc");
    }
    
    NSString *frame = [xmlDoc valueForKey:@"Frame"];
    
    NSLog(@"Output: %@", frame);

**Comment by nicklockwood** [comment]
@balistrerin not quite. ` [[NSBundle mainBundle] pathForResource:]` is only for finding files in the application bundle. If you want a file on  your desktop, you would just write:

    NSString *filePath = @"/Users/mycomputer/Desktop/foo.xml";

The rest is correct.

**Comment by balistrerin** [comment]
Ah thank you so much.  That was it.  So I now have another issue where when I:

    NSLog(@"Output: %@", frame);

I have 960 frames but it is only printing out the first 87 frames.  Is there any reason why that could be happening?

**Comment by nicklockwood** [comment]
if "frame" is an array, xcode might just be truncating it when it prints. Try:

NSLog(@"frame count %i", frame.count);

**Comment by nicklockwood** [comment]
If not, it's possible that there is an error in the xml file around node 88 (e.g a missing tag), and so the parser is stopping at that point.

**Comment by nicklockwood** [comment]
👍
